jobs:
  include:
    - stage: "Build"
      script:
        - docker build -t php7-fpm .
        - docker images
    - stage: "Test"
      script:
        - docker images
    - stage: 'Deploy'
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin